# random min and max values
min_default_location: -2500
max_default_location: 2500

# random settings
default_invulnerability_ticks: 6000

# Auto Save-All settings
# saving message
saveingmsg: Saving...

# saving complete message
saveingmsgcomplete: Save complete!

# savealltimer & warningdelay are in mins
savealltimer: 60
warningdelay: 10

#Auto broadcast settings
broadcastmessages:
  - Vote for OASIS at bit.ly/oasisv for 150 coins!
  - Apply for member at bit.ly/OasisMember
  - Donate for the server at bit.ly/ODonate
# also in minutes
broadcasttimer: 30

#New player join msg
newplayermsg: '&dWelcome &f{DISPLAYNAME}&d to Oasis SMP!'

#New player kit
newbiekit:
  - 268
  - 269
  - 270
  - 271
  - 290

# Frozen players
#frozen: {} to clear the list
frozen: {}