# random min and max values
min_default_location: -2500
max_default_location: 2500
  
motd: 'Welcome to Oasis SMP!'
motdcolor: 'random'
  
msgallformat: '&6[{DISPLAYNAME}&6-> me] {MESSAGE}'

# random settings
default_invulnerability_ticks: 300

# also in minutes
broadcasttimer: 15
  
#Custom join/quit/kick msgs!
join: '&e{DISPLAYNAME} joined the game!'
quit: '&e{DISPLAYNAME} left the game!'
kick: '&e{DISPLAYNAME} was &cKICKED &efrom the game!'
  
#Auto broadcast settings
broadcastmessages:
  - Vote for OASIS at bit.ly/oasisv for 150 coins!
  - Apply for member at bit.ly/OasisMember
  - Donate for the server at bit.ly/ODonate
  - Want to switch worlds? Type /warp world1 for the old world, and /warp world2 for the new world!
  
#Apple Tree settings
#Delay before a new tree produces apples, in ticks.
# 1 min = 1200, 1 MC day = 20 mins = 24000 ticks
AppleProduceDelay: 24000
Percent: 2
maxdistance: 15

#Hoard ownergame world
gameworld: ownergames
radius: 30

IgnoreMadV: false
IgnorePaxStop: false
