name: OasisExtras
main: net.charter.orion_pax.OasisExtras.OasisExtras
version: 2.0
description: Oasis Extra commands!
author: Paxination
commands:
    
  blackmarket:
    description: Blackmarket broadcast
    aliases: [bm, bmarket]
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.blackmarket
    permission-message: You don't have permissions for <permission>
    
  givecoupon:
    description: Gives coupons to players on pixelmon server!
    aliases: [gc, givecoup, gcoup]
    usage: "Usage: /<command> (player) (amount)"
    permission: oasisextras.staff.givecoupon
    permission-message: You don't have permissions for <permission>
    
  comcast:
    description: ComCast broadcast
    aliases: [cc, ccast]
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.comcast
    permission-message: You don't have permissions for <permission>
    
  kcast:
    description: Voice of the PEOPLE!  Another broadcast....
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.kcast
    permission-message: You don't have permissions for <permission>
    
  findme:
    description: Search for playernames.
    aliases: [os, offsearch, searchname, psearch]
    usage: "Usage: /<command> name"
    permission: oasisextras.staff.findme
    permission-message: You don't have permissions for <permission>
    
  oasisextras:
    description:  Reloads OasisExtras config
    aliases: [oe]
    usage:
    permission: oasisextras.staff.oasisextras
    permission-message: You don't have permissions for <permission>
    
  random:
    description:  TP to a random location!
    usage:
    permission: oasisextras.player.random
    permission-message: You don't have permissions for <permission>
    
  enableme:
    description:  Funny broadcast message!
    aliases: eme
    usage:
    permission: oasisextras.staff.enableme
    permission-message: You don't have permissions for <permission>
    
  disableme:
    description:  Funny broadcast message!
    aliases: dme
    usage:
    permission: oasisextras.staff.disableme
    permission-message: You don't have permissions for <permission>
    
  brocast:
    description: Broadcasts a msg with prefix [Brocast] instead of [Broadcast]
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.brocast
    permission-message: You don't have permissions for <permission>
    
  chant:
    description: Broadcasts a msg
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.chant
    permission-message: You don't have permissions for <permission>
    
  thunderstruck:
    description: Broadcasts a msg
    aliases: strike
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.thunderstruck
    permission-message: You don't have permissions for <permission>
    
  spook:
    description: Plays a sound effect at the specified player
    usage: "Usage: /<command> playername [#1-10 optional]"
    permission: oasisextras.staff.spook
    permission-message: You don't have permissions for <permission>
    
  freeze:
    description: Freezes the player in their tracks.
    usage: "Usage: /<command> playername"
    permission: oasisextras.staff.freeze
    permission-message: You don't have permissions for <permission>
    
  drunk:
    description: Makes players screen look like they are drunk!
    usage: "Usage: /<command> playername [seconds (optional)]"
    permission: oasisextras.staff.drunk
    permission-message: You don't have permissions for <permission>
    
  slap:
    description: Slaps a player!
    usage: "Usage: /<command> playername [msg] (msg is optional)"
    permission: oasisextras.staff.slap
    permission-message: You don't have permissions for <permission>
    
  spank:
    description: Spanks a player!
    usage: "Usage: /<command> playername [msg] (msg is optional)"
    permission: oasisextras.staff.spank
    permission-message: You don't have permissions for <permission>
    
  mount:
    description: Mounts a player!
    usage: "Usage: /<command> playername [playername] (second one optional)"
    permission: oasisextras.staff.mount
    permission-message: You don't have permissions for <permission>
    
  dismount:
    description: Forces a player to dismount you!
    usage: "Usage: /<command>"
    permission: oasisextras.player.dismount
    permission-message: You don't have permissions for <permission>
    
  findschem:
    description: Searches worldedit schematics!
    aliases: [fschem,fs]
    usage: "Usage: /<command> schematic name"
    permission: oasisextras.staff.findschem
    permission-message: You don't have permissions for <permission>
    
  tempperm:
    description: Adds a temporary permnode to a player!
    aliases: [tperm]
    usage: "Usage: /<command> <player> <permnode>"
    permission: oasisextras.staff.tempperm
    permission-message: You don't have permissions for <permission>
    
  shit:
    description: Shits on a player with notification!
    aliases: [shat, crap, so, shiton, shaton, crapon]
    usage: "Usage: /<command> <player>"
    permission: oasisextras.staff.shit
    permission-message: You don't have permissions for <permission>
    
permissions:
    oasisextras.staff.blackmarket:
        description: Blackmarket broadcast!
        
    oasisextras.staff.givecoupon:
        description: Gives coupons to players on pixelmon server!
        
    oasisextras.staff.comcast:
        description: Comcast broadcast!
        
    oasisextras.staff.kcast:
        description: KCast broadcast!
        
    oasisextras.staff.findme:
        description: Search for usernames!
        
    oasisextras.staff.oasisextras:
        description: OE Ops only commands!
        
    oasisextras.player.random:
        description: Randomly TP's a player around the map!
        
    oasisextras.staff.enableme:
        description: Funny broadcast message!
        
    oasisextras.staff.disableme:
        description: Funny broadcast message!
        
    oasisextras.staff.brocast:
        description: Brocast instead of broadcast!
        
    oasisextras.staff.chant:
        description: Custom broadcast msgs!
        
    oasisextras.staff.thunderstruck:
        description: Strike thunder at your location.
        
    oasisextras.staff.spook:
        description: Spooks a player!
        
    oasisextras.staff.freeze:
        description: Freezes a player!
        
    oasisextras.staff.drunk:
        description: Makes a player drunk!
        
    oasisextras.staff.slap:
        description: Slaps a bitch!
        
    oasisextras.staff.spank:
        description: Spanks a bitch!
        
    oasisextras.staff.mount:
        description: Mounts a player!
        
    oasisextras.player.dismount:
        description: Player command to force staff to dismount them.
        
    oasisextras.staff.findschem:
        description: Search the schematics folder.
        
    oasisextras.staff.tempperm:
        description: Gives a permnode temporarily.  Log out and its gone.
        
    oasisextras.staff.shit:
        description: Shit on a player!
        
    oasisextras.player.appletree:
        description: Allows a player to spawn an appletree!
        
    oasisextras.player.catndog:
        description: Allows players to spawn a cat or a dog with fish or bones!
        
    oasisextras.player.tp:
        description: Allows a player to tp their animals.
        
    oasisextras.staff.teleportall:
        description: Allows staff to tp any mob, not just animals.
        
    oasisextras.staff.staff:
        description: Staff perm node check for OE!
        
    oasisextras.player.*:
        description: Gives access to all player commands
        children:
            oasisextras.player.appletree: true
            oasisextras.player.catndog: true
            oasisextras.player.random: true
            oasisextras.player.highfive: true
            oasisextras.player.tp: true
            oasisextras.player.dismount: true
            
    oasisextras.staff.pixelmon:
        description: Pixelmon specific permnodes
        children:
            oasisextras.staff.comcast: true
            oasisextras.staff.blackmarket: true
            oasisextras.staff.givecoupon: true
            
    oasisextras.staff.mod:
        description: Mod perm nodes
        children:
            oasisextras.staff.givecoupon: true
            oasisextras.staff.thunderstruck: true
            oasisextras.staff.bcastadd: true
            oasisextras.staff.bcastdel: true
            oasisextras.staff.bcastlist: true
            oasisextras.staff.mount: true
                        
    oasisextras.staff.jrmod:
        description: JrMod perm nodes
        children:
            oasisextras.staff.teleportall: true
            oasisextras.staff.findschem: true
            oasisextras.staff.staff: true
            oasisextras.staff.getowner: true
            oasisextras.staff.override: true
            oasisextras.staff.enableme: true
            oasisextras.staff.disableme: true
            oasisextras.staff.freeze: true
            oasisextras.staff.drunk: true
            oasisextras.staff.slap: true
            oasisextras.staff.spook: true
            oasisextras.staff.findme: true