name: OasisExtras
main: net.charter.orion_pax.OasisExtras.OasisExtras
version: 2.0
description: Oasis Extra commands!
author: Paxination
commands:
  kcast:
    description: Voice of the PEOPLE!
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.kcast
    permission-message: You don't have permissions for <permission>
  findme:
    description: Find an offline user!
    aliases: [os, offsearch, searchname, psearch]
    usage:
    permission: oasisextras.staff.findme
    permission-message: You don't have permissions for <permission>
  bdaccept:
    description: Accept a buildoff invitation!
    usage:
    permission: oasisextras.player.bdaccept
    permission-message: You don't have permissions for <permission>
  bddeny:
    description: Deny a buildoff invitation!
    usage:
    permission: oasisextras.player.bddeny
    permission-message: You don't have permissions for <permission>
  buildoff:
    description: Start a buildoff!
    usage:
    permission: oasisextras.staff.buildoff
    permission-message: You don't have permissions for <permission>
  payback:
    description:  Get yo payback on!
    usage:
    permission: oasisextras.staff.payback
    permission-message: You don't have permissions for <permission>
  alock:
    description:  Locks animal to a player.
    usage:
    permission: oasisextras.player.alock
    permission-message: You don't have permissions for <permission>
  hoard:
    description:  Hoard command!
    usage:
    permission: oasisextras.staff.hoard
    permission-message: You don't have permissions for <permission>
  animalregen:
    description:  Randomly spawns animals in a radius.
    aliases: ar
    usage:
    permission: oasisextras.staff.animalregen
    permission-message: You don't have permissions for <permission>
    
  timer:
    description:  Starts an in game timer!
    usage:
    permission: oasisextras.staff.timer
    permission-message: You don't have permissions for <permission>
    
  oasisextras:
    description:  Reloads OasisExtras config
    aliases: oe
    usage:
    permission: oasisextras.staff.oasisextras
    permission-message: You don't have permissions for <permission>
    
  random:
    description:  TP to a random location!
    usage:
    permission: oasisextras.player.random
    permission-message: You don't have permissions for <permission>
    
  enableme:
    description:  Funny broadcast message!
    aliases: eme
    usage:
    permission: oasisextras.staff.enableme
    permission-message: You don't have permissions for <permission>
    
  disableme:
    description:  Funny broadcast message!
    aliases: dme
    usage:
    permission: oasisextras.staff.disableme
    permission-message: You don't have permissions for <permission>
    
  brocast:
    description: Broadcasts a msg with prefix [Brocast] instead of [Broadcast]
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.brocast
    permission-message: You don't have permissions for <permission>
    
  chant:
    description: Broadcasts a msg
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.chant
    permission-message: You don't have permissions for <permission>
    
  thunderstruck:
    description: Broadcasts a msg
    aliases: strike
    usage: "Usage: /<command> Your message here!"
    permission: oasisextras.staff.thunderstruck
    permission-message: You don't have permissions for <permission>
    
  spook:
    description: Plays a sound effect at the specified player
    usage: "Usage: /<command> playername [#1-10 optional]"
    permission: oasisextras.staff.spook
    permission-message: You don't have permissions for <permission>
    
  freeze:
    description: Freezes the player in their tracks.
    usage: "Usage: /<command> playername"
    permission: oasisextras.staff.freeze
    permission-message: You don't have permissions for <permission>
    
  drunk:
    description: Makes players screen look like they are drunk!
    usage: "Usage: /<command> playername [seconds (optional)]"
    permission: oasisextras.staff.drunk
    permission-message: You don't have permissions for <permission>
    
  slap:
    description: Slaps a player!
    usage: "Usage: /<command> playername [msg] (msg is optional)"
    permission: oasisextras.staff.slap
    permission-message: You don't have permissions for <permission>
    
  mount:
    description: Mounts a player!
    usage: "Usage: /<command> playername [playername] (second one optional)"
    permission: oasisextras.staff.mount
    permission-message: You don't have permissions for <permission>
    
  unmount:
    description: Unmounts a player!
    usage: "Usage: /<command>"
    permission: oasisextras.staff.unmount
    permission-message: You don't have permissions for <permission>
    
permissions:
    oasisextras.player.*:
        description: Gives access to all player commands
        children:
            oasisextras.player.appletree: true
            oasisextras.player.catndog: true
            oasisextras.player.random: true
            oasisextras.player.alock: true
            oasisextras.player.bdaccept: true
            oasisextras.player.bddeny: true
            
    oasisextras.staff.mod:
        description: Gives access to all staff commands
        children:
            oasisextras.staff.buildoff: true
            oasisextras.staff.hoard: true
            oasisextras.staff.thunderstruck: true
            oasisextras.staff.bcastadd: true
            oasisextras.staff.bcastdel: true
            oasisextras.staff.bcastlist: true
            oasisextras.staff.mount: true
            oasisextras.staff.unmount: true
            
    oasisextras.staff.guide:
        description: Guide perm nodes
        children:
            oasisextras.staff.timer: true
            oasisextras.staff.enableme: true
            oasisextras.staff.disableme: true
            oasisextras.staff.freeze: true
            oasisextras.staff.drunk: true
            oasisextras.staff.slap: true
            oasisextras.staff.spook: true